import type { IconType } from "react-icons";
import {
  GiAcid,
  GiAcrobatic,
  GiAnatomy,
  GiAngelOutfit,
  GiAnvil,
  GiAnvilImpact,
  GiArcher,
  GiArcheryTarget,
  GiArmorDowngrade,
  GiArmorUpgrade,
  GiArmSling,
  GiBabyFace,
  GiBackstab,
  GiBallGlow,
  GiBandageRoll,
  GiBed,
  GiBeerStein,
  GiBleedingHeart,
  GiBlindfold,
  GiBodyBalance,
  GiBoar,
  GiBoneKnife,
  GiBookmark,
  GiBoots,
  GiBowArrow,
  GiBrain,
  GiBreastplate,
  GiBrokenShield,
  GiCampfire,
  GiCampCookingPot,
  GiCaveEntrance,
  GiCaveman,
  GiCavalry,
  GiComa,
  GiCompass,
  GiConversation,
  GiConvince,
  GiCow,
  GiCrafting,
  GiCrackedShield,
  GiCrossedSwords,
  GiConversation as GiDebateFallback,
  GiDecapitation,
  GiDespair,
  GiDiceTwentyFacesOne,
  GiDiceTwentyFacesTwenty,
  GiDiabloSkull,
  GiDisintegrate,
  GiDiscussion,
  GiDodging,
  GiDominoMask,
  GiDramaMasks,
  GiDragonHead,
  GiDrowning,
  GiDungeonGate,
  GiDwarfFace,
  GiEyelashes,
  GiEmptyHourglass,
  GiEmbrassedEnergy,
  GiExtraLucid,
  GiFairy,
  GiFalling,
  GiFeather,
  GiFlame,
  GiFlyingShuriken,
  GiFootprint,
  GiGoblinHead,
  GiGrab,
  GiGuitar,
  GiHalberd,
  GiHammerNails,
  GiHand,
  GiHandSaw,
  GiHarpoonTrident,
  GiHeartBottle,
  GiHeartShield,
  GiHeavyArrow,
  GiHearingDisabled,
  GiHiking,
  GiHoodedAssassin,
  GiHoodedFigure,
  GiHolyGrail,
  GiHolySymbol,
  GiHood,
  GiHorseshoe,
  GiIceBolt,
  GiIceSpellCast,
  GiIdCard,
  GiIfrit,
  GiImp,
  GiImprisoned,
  GiInternalInjury,
  GiInvisible,
  GiJourney,
  GiJuggler,
  GiJumpAcross,
  GiDoorHandle,
  GiKnockout,
  GiKnapsack,
  GiKoala,
  GiLeapfrog,
  GiLeatherVest,
  GiLift,
  GiLightningTrio,
  GiLockpicks,
  GiMagicHat,
  GiMagicLamp,
  GiMagicSwirl,
  GiMagnifyingGlass,
  GiManacles,
  GiMasterOfArms,
  GiMeal,
  GiMinions,
  GiMountainClimbing,
  GiNightVision,
  GiNunFace,
  GiOgre,
  GiOldWagon,
  GiOpenBook,
  GiOrcHead,
  GiPaintBrush,
  GiPaintedPottery,
  GiPathDistance,
  GiPerson,
  GiPerspectiveDiceSixFacesRandom,
  GiPiercedBody,
  GiPoisonBottle,
  GiPoisonGas,
  GiPoolDive,
  GiPotionBall,
  GiProgression,
  GiPsychicWaves,
  GiPull,
  GiPush,
  GiQuakeStomp,
  GiRallyTheTroops,
  GiBloodySword,
  GiRelicBlade,
  GiRingBox,
  GiRobber,
  GiRockGolem,
  GiRollingDices,
  GiRoundShield,
  GiRuneStone,
  GiRun,
  GiSaberAndPistol,
  GiSaberSlash,
  GiSandsOfTime,
  GiScreaming,
  GiScrollQuill,
  GiSemiClosedEye,
  GiShakingHands,
  GiSharpSmile,
  GiShield,
  GiShotgun,
  GiSleepy,
  GiSmitten,
  GiSnatch,
  GiSonicScreech,
  GiSpellBook,
  GiSpotedFlower,
  GiSprint,
  GiSquidHead,
  GiStoneAxe,
  GiStoneCrafting,
  GiStoneSphere,
  GiStrong,
  GiSundial,
  GiSunkenEye,
  GiSuperMushroom,
  GiSurprised,
  GiSwordHilt,
  GiSwordWound,
  GiTelepathy,
  GiThirdEye,
  GiTiredEye,
  GiTinker,
  GiTorch,
  GiTreasureMap,
  GiUltrasound,
  GiWaxSeal,
  GiWineGlass,
  GiWizardFace,
  GiWizardStaff,
  GiWomanElfFace,
  GiWoodClub,
  GiWool,
  GiYinYang,
} from "react-icons/gi";

export const ICON_MAP: Record<string, IconType> = {
  "acid": GiAcid,
  "acrobatic": GiAcrobatic,
  "anatomy": GiAnatomy,
  "angel-outfit": GiAngelOutfit,
  "anvil": GiAnvil,
  "anvil-impact": GiAnvilImpact,
  "archer": GiArcher,
  "archery-target": GiArcheryTarget,
  "armor-downgrade": GiArmorDowngrade,
  "armor-upgrade": GiArmorUpgrade,
  "arm-sling": GiArmSling,
  "baby-face": GiBabyFace,
  "backstab": GiBackstab,
  "ball-glow": GiBallGlow,
  "bandage-roll": GiBandageRoll,
  "bed": GiBed,
  "beer-stein": GiBeerStein,
  "bleeding-heart": GiBleedingHeart,
  "blindfold": GiBlindfold,
  "body-balance": GiBodyBalance,
  "boar": GiBoar,
  "bone-knife": GiBoneKnife,
  "bookmark": GiBookmark,
  "boots": GiBoots,
  "bow-arrow": GiBowArrow,
  "brain": GiBrain,
  "breastplate": GiBreastplate,
  "broken-shield": GiBrokenShield,
  "campfire": GiCampfire,
  "camp-cooking-pot": GiCampCookingPot,
  "cave-entrance": GiCaveEntrance,
  "caveman": GiCaveman,
  "cavalry": GiCavalry,
  "coma": GiComa,
  "compass": GiCompass,
  "conversation": GiConversation,
  "convince": GiConvince,
  "cow": GiCow,
  "crafting": GiCrafting,
  "cracked-shield": GiCrackedShield,
  "crossed-swords": GiCrossedSwords,
  "debate": GiDebateFallback,
  "decapitation": GiDecapitation,
  "despair": GiDespair,
  "dice-twenty-faces-one": GiDiceTwentyFacesOne,
  "dice-twenty-faces-twenty": GiDiceTwentyFacesTwenty,
  "diablo-skull": GiDiabloSkull,
  "disintegrate": GiDisintegrate,
  "discussion": GiDiscussion,
  "dodging": GiDodging,
  "domino-mask": GiDominoMask,
  "drama-masks": GiDramaMasks,
  "dragon-head": GiDragonHead,
  "drowning": GiDrowning,
  "dungeon-gate": GiDungeonGate,
  "dwarf-face": GiDwarfFace,
  "eyelashes": GiEyelashes,
  "empty-hourglass": GiEmptyHourglass,
  "embrassed-energy": GiEmbrassedEnergy,
  "extra-lucid": GiExtraLucid,
  "fairy": GiFairy,
  "falling": GiFalling,
  "feather": GiFeather,
  "flame": GiFlame,
  "flying-shuriken": GiFlyingShuriken,
  "footprint": GiFootprint,
  "goblin-head": GiGoblinHead,
  "grab": GiGrab,
  "guitar": GiGuitar,
  "halberd": GiHalberd,
  "hammer-nails": GiHammerNails,
  "hand": GiHand,
  "hand-saw": GiHandSaw,
  "harpoon-trident": GiHarpoonTrident,
  "heart-bottle": GiHeartBottle,
  "heart-shield": GiHeartShield,
  "heavy-arrow": GiHeavyArrow,
  "hearing-disabled": GiHearingDisabled,
  "hiking": GiHiking,
  "hooded-assassin": GiHoodedAssassin,
  "hooded-figure": GiHoodedFigure,
  "holy-grail": GiHolyGrail,
  "holy-symbol": GiHolySymbol,
  "hood": GiHood,
  "horse": GiHorseshoe,
  "ice-bolt": GiIceBolt,
  "ice-spell-cast": GiIceSpellCast,
  "id-card": GiIdCard,
  "ifrit": GiIfrit,
  "imp": GiImp,
  "imprisoned": GiImprisoned,
  "internal-injury": GiInternalInjury,
  "invisible": GiInvisible,
  "journey": GiJourney,
  "juggler": GiJuggler,
  "jump-across": GiJumpAcross,
  "knock-it": GiDoorHandle,
  "knockout": GiKnockout,
  "knapsack": GiKnapsack,
  "koala": GiKoala,
  "leapfrog": GiLeapfrog,
  "leather-vest": GiLeatherVest,
  "lift": GiLift,
  "lightning-trio": GiLightningTrio,
  "lockpicks": GiLockpicks,
  "magic-hat": GiMagicHat,
  "magic-lamp": GiMagicLamp,
  "magic-swirl": GiMagicSwirl,
  "magnifying-glass": GiMagnifyingGlass,
  "manacles": GiManacles,
  "master-of-arms": GiMasterOfArms,
  "meal": GiMeal,
  "minions": GiMinions,
  "mountain-climbing": GiMountainClimbing,
  "night-vision": GiNightVision,
  "nun-face": GiNunFace,
  "ogre": GiOgre,
  "old-wagon": GiOldWagon,
  "open-book": GiOpenBook,
  "orc-head": GiOrcHead,
  "paint-brush": GiPaintBrush,
  "painted-pottery": GiPaintedPottery,
  "path-distance": GiPathDistance,
  "person": GiPerson,
  "perspective-dice-six-faces-random": GiPerspectiveDiceSixFacesRandom,
  "pierced-body": GiPiercedBody,
  "poison-bottle": GiPoisonBottle,
  "poison-gas": GiPoisonGas,
  "pool-dive": GiPoolDive,
  "potion-ball": GiPotionBall,
  "progression": GiProgression,
  "psychic-waves": GiPsychicWaves,
  "pull": GiPull,
  "push": GiPush,
  "quake-stomp": GiQuakeStomp,
  "rally-the-troops": GiRallyTheTroops,
  "red-hand": GiBloodySword,
  "relic-blade": GiRelicBlade,
  "ring-box": GiRingBox,
  "robber": GiRobber,
  "rock-golem": GiRockGolem,
  "rolling-dices": GiRollingDices,
  "round-shield": GiRoundShield,
  "rune-stone": GiRuneStone,
  "run": GiRun,
  "saber-and-pistol": GiSaberAndPistol,
  "saber-slash": GiSaberSlash,
  "sands-of-time": GiSandsOfTime,
  "screaming": GiScreaming,
  "scroll-quill": GiScrollQuill,
  "semi-closed-eye": GiSemiClosedEye,
  "shaking-hands": GiShakingHands,
  "sharp-smile": GiSharpSmile,
  "shield": GiShield,
  "shotgun": GiShotgun,
  "sleepy": GiSleepy,
  "smitten": GiSmitten,
  "snatch": GiSnatch,
  "sonic-screech": GiSonicScreech,
  "spell-book": GiSpellBook,
  "spoted-flower": GiSpotedFlower,
  "sprint": GiSprint,
  "squid-head": GiSquidHead,
  "stone-axe": GiStoneAxe,
  "stone-crafting": GiStoneCrafting,
  "stone-sphere": GiStoneSphere,
  "strong": GiStrong,
  "sundial": GiSundial,
  "sunken-eye": GiSunkenEye,
  "super-mushroom": GiSuperMushroom,
  "surprised": GiSurprised,
  "sword-hilt": GiSwordHilt,
  "sword-wound": GiSwordWound,
  "telepathy": GiTelepathy,
  "third-eye": GiThirdEye,
  "tired-eye": GiTiredEye,
  "tinker": GiTinker,
  "torch": GiTorch,
  "treasure-map": GiTreasureMap,
  "ultrasound": GiUltrasound,
  "wax-seal": GiWaxSeal,
  "wine-glass": GiWineGlass,
  "wizard-face": GiWizardFace,
  "wizard-staff": GiWizardStaff,
  "woman-elf-face": GiWomanElfFace,
  "wood-club": GiWoodClub,
  "wool": GiWool,
  "yin-yang": GiYinYang,
};
